<?php

namespace SendSMS\SendsmsLaravel\API;

use ReflectionMethod;

class ApiKey extends ApiCommunication
{
    /**
     *   Add a new IP to the API Key whitelist
     *  
     *   @global string $username
     *   @global string $password
     *   @param string $ipaddr: The IP to whitelist
     */
    function token_add_ip($ipaddr)
    {
        $args = func_get_args();
        return $this->call_api_action(new ReflectionMethod(__CLASS__, __FUNCTION__), $args);
    }

    /**
     *   List all whitelisted IPs of the API Key
     *  
     *   @global string $username
     *   @global string $password
     */
    function token_list_ips()
    {
        $args = func_get_args();
        return $this->call_api_action(new ReflectionMethod(__CLASS__, __FUNCTION__), $args);
    }

    /**
     *   Authorization of the key generated by user_authorize_application
     *  
     *   @global string $username
     *   @global string $password
     *   @param string $request_key: The key returned by user_authorize_application
     */
    function user_allow_token_request($request_key)
    {
        $args = func_get_args();
        return $this->call_api_action(new ReflectionMethod(__CLASS__, __FUNCTION__), $args);
    }

    /**
     *   This action allows a third party application to get an authentication key in order to make use of a user's account.
     *
     *   @param string $application_name: The name of the application to be authorized (for the user to see)
     */
    function user_authorize_application($application_name)
    {
        $args = func_get_args();
        return $this->call_api_action(new ReflectionMethod(__CLASS__, __FUNCTION__), $args, false);
    }

    /**
     *   Get the API Key
     *
     *   @param string request_key: The original request key returned from user_authorize_application()
     */
    function user_get_api_key($request_key)
    {
        $args = func_get_args();
        return $this->call_api_action(new ReflectionMethod(__CLASS__, __FUNCTION__), $args, false);
    }
}
